version: "3"
services:

  sql-server-db:
    container_name: sql-server-db
    build:
        context: ./sql-server-db
        dockerfile: Dockerfile
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "1234testdb!"
      ACCEPT_EULA: "Y"

  flask-app:
    build:
      context: ./flask-app
      dockerfile: Dockerfile
    ports:
      - "5000:5000"